import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import HomePage from './Home';

export default function Home() {


  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <title>Baião Rock Bar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomePage />
    </>
  )
}
