import Head from 'next/head'
import styles from '../../styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <link rel="icon" href="/beer.ico" />
        <title>Baião Rock Bar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <p>Ola mundo</p>
      </div>
      
    </>
  )
}
